### ISSUE TITLE
Options ?

### ISSUE THREAD

**Issue by bonnebulle** [Rectar2/node-ffplay#1]
Hello, thank, great little tool !
I would like to use options like :
`ffplay -autoexit -nodisp hello.wav`
that is possible with node-ffplay ?
I dont find more documentation...
thanks

**Comment by k80w** [comment]
I can get around to adding support for custom options later today, but if all you need is `-autoexit -nodisp`, those are both automatic! When the code runs ffplay it runs something similar to this:
```bash
ffplay $FILE -nodisp -autoexit
```

**Comment by k80w** [comment]
Done! You can check the README file for usage <3

**Comment by bonnebulle** [comment]
Cool, thanks for the documentation/instructions...
Am not sure -autoexit -nodisp by default is a great thing ;)
There is an option to enable display (like -yesdisp) ?
Thanks, am searching (and kiding) ;)

I try to use ffplay has a playlist player + random
(right now am using m3u... not realy flexible)
